name = "PurplesPack"
author = "PrpleMoon"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81f7fdda61257bf1cc3ca0249ec646c2e9942a1e316c99f2a70d4f38a97efbec"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
