name = "PurplesPack"
author = "PrpleMoon"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "913c103c03b9c25c64b7c6e84831227f9e62522966fd0f19e41de103d3f1d2cc"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
