name = "PurplesPack"
author = "PrpleMoon"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81d20df14d6eedeeadeb64ec7b44b257b59ddd9e12fe5a8f11ce423eb656e812"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
