name = "PurplesPack"
author = "PrpleMoon"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fdb8fcaabead83c60b00b614d1803b1d7c49a49dc7327f3659fb5fcef9698ab"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
