name = "PurplesPack"
author = "PrpleMoon"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae9b9a32ecdb6d3f1832b6ed4210303a02ba82bf7ef236ae7981b1336585e8bc"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
