name = "PurplesPack"
author = "PrpleMoon"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "665738e41a0eebbb92ec70bfa64ab583f0ac339fbd5db7fcec026d4e827e8da6"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
