name = "Purple's Pack"
author = "PrpleMoon"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "212fa776481f79ab9fedaa0f9c84421f159c094e953ce1d298fed83ce7492648"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
