name = "Purple's Pack"
author = "PrpleMoon"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9192b386b5994844b241440cdab10a60ed0bb1ec26f3f3d8da288b90a48c1bd"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
