name = "Purple's Pack"
author = "PrpleMoon"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26791b4302998ecb173c69b3eb25cd11f52cc691f4c52fdf00cecb0c6eef8a3b"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
