name = "PurplesPack"
author = "PrpleMoon"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fc5605313bc38311eec0c9b0b8618ca5e9a300d8d23e4a139e3abb488a8b4aa"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
