name = "PurplesPack"
author = "PrpleMoon"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4821b68e127118bf98a11c7a974cf1d69ac1221cf2319696a71af91672ff7e31"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
