name = "PurplesPack"
author = "PrpleMoon"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "872baeeba283b3e336f441a1b4c54c75f14142e4381ec00f4214f22aa63ab09f"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
