name = "PurplesPack"
author = "PrpleMoon"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecbbad0f8a83b9ecef80affcd49260e04e90b0630f226302cc0057a8fd1ea0a8"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
