name = "Purples Pack"
author = "PrpleMoon"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f2470243e255339a19108b48be30b68b6242e362dba52d908677bace97dffa1"

[versions]
minecraft = "1.20.4"
quilt = "0.23.1"
